"""
    XYO RESTful Transaction Enrichment API

    RESTful API for enriching financial transactions.

    The version of the OpenAPI document: 2.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr
from typing import List, Optional
from typing_extensions import Annotated
from uuid import UUID
from xyo._generated.models.enrich_transaction_collection_response import EnrichTransactionCollectionResponse
from xyo._generated.models.enrich_transactions_request_inner import EnrichTransactionsRequestInner
from xyo._generated.models.enrichment_collection_status_response import EnrichmentCollectionStatusResponse
from xyo._generated.models.enrichment_request import EnrichmentRequest
from xyo._generated.models.enrichment_response import EnrichmentResponse

from xyo._generated.api_client import ApiClient, RequestSerialized
from xyo._generated.api_response import ApiResponse
from xyo._generated.rest import RESTResponseType


class EnrichmentApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    async def enrich_transaction(
        self,
        enrichment_request: Annotated[EnrichmentRequest, Field(description="Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.")],
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> EnrichmentResponse:
        """Transaction Enrichment

        Enrich a single financial transaction synchronously.

        :param enrichment_request: Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
        :type enrichment_request: EnrichmentRequest
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transaction_serialize(
            enrichment_request=enrichment_request,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def enrich_transaction_with_http_info(
        self,
        enrichment_request: Annotated[EnrichmentRequest, Field(description="Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.")],
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[EnrichmentResponse]:
        """Transaction Enrichment

        Enrich a single financial transaction synchronously.

        :param enrichment_request: Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
        :type enrichment_request: EnrichmentRequest
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transaction_serialize(
            enrichment_request=enrichment_request,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def enrich_transaction_without_preload_content(
        self,
        enrichment_request: Annotated[EnrichmentRequest, Field(description="Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code.")],
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Transaction Enrichment

        Enrich a single financial transaction synchronously.

        :param enrichment_request: Transaction enrichment request payload containing payment text and ISO-3166-1 alpha-2 country code. (required)
        :type enrichment_request: EnrichmentRequest
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transaction_serialize(
            enrichment_request=enrichment_request,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _enrich_transaction_serialize(
        self,
        enrichment_request,
        x_correlation_id,
        traceparent,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_correlation_id is not None:
            _header_params['X-Correlation-ID'] = x_correlation_id
        if traceparent is not None:
            _header_params['traceparent'] = traceparent
        # process the form parameters
        # process the body parameter
        if enrichment_request is not None:
            _body_params = enrichment_request


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/ai/finance/enrichment/transaction',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def enrich_transactions(
        self,
        enrich_transactions_request_inner: Annotated[List[EnrichTransactionsRequestInner], Field(min_length=1, max_length=50000, description="Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> EnrichTransactionCollectionResponse:
        """Transaction Enrichments

        Enrich a collection of financial transactions asynchronously.

        :param enrich_transactions_request_inner: Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
        :type enrich_transactions_request_inner: List[EnrichTransactionsRequestInner]
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transactions_serialize(
            enrich_transactions_request_inner=enrich_transactions_request_inner,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichTransactionCollectionResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def enrich_transactions_with_http_info(
        self,
        enrich_transactions_request_inner: Annotated[List[EnrichTransactionsRequestInner], Field(min_length=1, max_length=50000, description="Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[EnrichTransactionCollectionResponse]:
        """Transaction Enrichments

        Enrich a collection of financial transactions asynchronously.

        :param enrich_transactions_request_inner: Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
        :type enrich_transactions_request_inner: List[EnrichTransactionsRequestInner]
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transactions_serialize(
            enrich_transactions_request_inner=enrich_transactions_request_inner,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichTransactionCollectionResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def enrich_transactions_without_preload_content(
        self,
        enrich_transactions_request_inner: Annotated[List[EnrichTransactionsRequestInner], Field(min_length=1, max_length=50000, description="Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Transaction Enrichments

        Enrich a collection of financial transactions asynchronously.

        :param enrich_transactions_request_inner: Array of transaction enrichment requests (minimum 1, maximum 50,000 items) for asynchronous batch processing. (required)
        :type enrich_transactions_request_inner: List[EnrichTransactionsRequestInner]
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._enrich_transactions_serialize(
            enrich_transactions_request_inner=enrich_transactions_request_inner,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichTransactionCollectionResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _enrich_transactions_serialize(
        self,
        enrich_transactions_request_inner,
        x_api_user,
        x_correlation_id,
        traceparent,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
            'EnrichTransactionsRequestInner': '',
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        # process the query parameters
        # process the header parameters
        if x_api_user is not None:
            _header_params['x-api-user'] = x_api_user
        if x_correlation_id is not None:
            _header_params['X-Correlation-ID'] = x_correlation_id
        if traceparent is not None:
            _header_params['traceparent'] = traceparent
        # process the form parameters
        # process the body parameter
        if enrich_transactions_request_inner is not None:
            _body_params = enrich_transactions_request_inner


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/v1/ai/finance/enrichment/transactions',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    async def get_enrichment_status(
        self,
        id: Annotated[StrictStr, Field(description="The unique identifier of the asynchronous bulk enrichment job.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> EnrichmentCollectionStatusResponse:
        """Transaction Enrichments Status

        Get the status of an asynchronous bulk enrichment job.

        :param id: The unique identifier of the asynchronous bulk enrichment job. (required)
        :type id: str
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_enrichment_status_serialize(
            id=id,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentCollectionStatusResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    async def get_enrichment_status_with_http_info(
        self,
        id: Annotated[StrictStr, Field(description="The unique identifier of the asynchronous bulk enrichment job.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[EnrichmentCollectionStatusResponse]:
        """Transaction Enrichments Status

        Get the status of an asynchronous bulk enrichment job.

        :param id: The unique identifier of the asynchronous bulk enrichment job. (required)
        :type id: str
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_enrichment_status_serialize(
            id=id,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentCollectionStatusResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        await response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    async def get_enrichment_status_without_preload_content(
        self,
        id: Annotated[StrictStr, Field(description="The unique identifier of the asynchronous bulk enrichment job.")],
        x_api_user: Annotated[Optional[StrictStr], Field(description="Optional identifier for the API user or tenant.")] = None,
        x_correlation_id: Annotated[Optional[UUID], Field(description="Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.")] = None,
        traceparent: Annotated[Optional[StrictStr], Field(description="Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Transaction Enrichments Status

        Get the status of an asynchronous bulk enrichment job.

        :param id: The unique identifier of the asynchronous bulk enrichment job. (required)
        :type id: str
        :param x_api_user: Optional identifier for the API user or tenant.
        :type x_api_user: str
        :param x_correlation_id: Unique caller correlation identifier (UUIDv4) for distributed tracing across microservice boundaries.
        :type x_correlation_id: UUID
        :param traceparent: Standard W3C TraceContext header (version-trace_id-parent_id-trace_flags) for distributed APM tracing.
        :type traceparent: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._get_enrichment_status_serialize(
            id=id,
            x_api_user=x_api_user,
            x_correlation_id=x_correlation_id,
            traceparent=traceparent,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "EnrichmentCollectionStatusResponse",
            '429': "ErrorResponse",
            '3XX': "ErrorResponse",
            '4XX': "ErrorResponse",
            '5XX': "ErrorResponse",
        }
        response_data = await self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _get_enrichment_status_serialize(
        self,
        id,
        x_api_user,
        x_correlation_id,
        traceparent,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if id is not None:
            _path_params['id'] = id
        # process the query parameters
        # process the header parameters
        if x_api_user is not None:
            _header_params['x-api-user'] = x_api_user
        if x_correlation_id is not None:
            _header_params['X-Correlation-ID'] = x_correlation_id
        if traceparent is not None:
            _header_params['traceparent'] = traceparent
        # process the form parameters
        # process the body parameter


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json'
                ]
            )


        # authentication setting
        _auth_settings: List[str] = [
            'BearerAuth'
        ]

        return self.api_client.param_serialize(
            method='GET',
            resource_path='/v1/ai/finance/enrichment/status/{id}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


