# coding: utf-8

"""
    XYO RESTful Transaction Enrichment API

    RESTful API for enriching financial transactions.

    The version of the OpenAPI document: 2.0.5
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class APIError(BaseModel):
    """
    RFC 7807 compliant problem details object representing an API error.
    """ # noqa: E501
    type: StrictStr = Field(description="A URI reference identifying the problem type.", json_schema_extra={"examples": ["https://api.xyo.financial/errors/unauthorized"]})
    title: StrictStr = Field(description="A short, human-readable summary of the problem type.", json_schema_extra={"examples": ["Unauthorized"]})
    status: StrictInt = Field(description="The HTTP status code generated by the origin server for this occurrence of the problem.", json_schema_extra={"examples": [401]})
    detail: StrictStr = Field(description="A human-readable explanation specific to this occurrence of the problem.", json_schema_extra={"examples": ["Invalid or expired Bearer authentication token provided."]})
    instance: StrictStr = Field(description="A URI reference identifying the specific occurrence of the problem.", json_schema_extra={"examples": ["/v1/ai/finance/enrichment/transaction#req-9b1deb4d-3b7d-4bad-9bdd-2b0d7b3dcb6d"]})
    __properties: ClassVar[List[str]] = ["type", "title", "status", "detail", "instance"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of APIError from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of APIError from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "type": obj.get("type"),
            "title": obj.get("title"),
            "status": obj.get("status"),
            "detail": obj.get("detail"),
            "instance": obj.get("instance")
        })
        return _obj


