# coding: utf-8

"""
    XYO RESTful Transaction Enrichment API

    RESTful API for enriching financial transactions.

    The version of the OpenAPI document: 2.0.8
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class EnrichmentResponse(BaseModel):
    """
    EnrichmentResponse
    """ # noqa: E501
    merchant: StrictStr = Field(description="Merchant is the name of the merchant.", json_schema_extra={"examples": ["Costa Coffee"]})
    description: StrictStr = Field(description="Description is a brief description of the merchant.", json_schema_extra={"examples": ["Costa Coffee is a British coffeehouse chain and a subsidiary of The Coca-Cola Company."]})
    categories: List[StrictStr] = Field(description="Categories lists categories fitting the description of the merchant.", json_schema_extra={"examples": [["Food & Beverage", "Cafes & Coffee Shops", "Dining Out"]]})
    logo: StrictStr = Field(description="Logo is a base64-encoded PNG or JPEG representing the merchant logo.", json_schema_extra={"examples": ["data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=="]})
    location: StrictStr = Field(description="Location describes the country and city. May be empty if the API returns null.", json_schema_extra={"examples": ["United Kingdom, London"]})
    address: StrictStr = Field(description="Address describes the exact address of purchase. May be empty if the API returns null.", json_schema_extra={"examples": ["40-42 Great Portland St, London W1W 7LZ"]})
    __properties: ClassVar[List[str]] = ["merchant", "description", "categories", "logo", "location", "address"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EnrichmentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EnrichmentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant": obj.get("merchant"),
            "description": obj.get("description"),
            "categories": obj.get("categories"),
            "logo": obj.get("logo"),
            "location": obj.get("location"),
            "address": obj.get("address")
        })
        return _obj


